//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuartzService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBJob
    {
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string JobGroup { get; set; }
        public string Process { get; set; }
        public string WorkingDirectory { get; set; }
        public string Arguments { get; set; }
        public string CronSchedule { get; set; }
        public Nullable<int> TimeOut { get; set; }
    }
}
