//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuartzService
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRecord
    {
        public int RecordId { get; set; }
        public Nullable<int> JobId { get; set; }
        public string JobName { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> TimedOut { get; set; }
    }
}
